# render.yaml
services:
  - type: web
    name: my-telegram-image-bot # Выберите имя для вашего сервиса на Render
    env: python
    runtimeVersion: python-3.11 # Указываем версию Python 3.11, совместимую с python-telegram-bot
    buildCommand: pip install -r requirements2.txt
    startCommand: python main2.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false # Значение будет взято из настроек окружения сервиса на Render
      - key: APP_URL
        sync: false # Значение будет взято из настроек окружения сервиса на Render
